Repository OCA/cooperative, pull requests merged in 2023-02, with the labels that each got.

#54 [12.0][FIX] cooperator: remove selection widget
  cooperator/readme/newsfragments/54.feature.rst
  cooperator/views/operation_request_view.xml
  cooperator/views/subscription_request_view.xml
  cooperator/wizard/create_subscription_from_partner.xml
Labels: bot is merging ⏳

#55 [14.0][FIX] cooperator: remove selection widget
  cooperator/readme/newsfragments/55.feature.rst
  cooperator/views/operation_request_view.xml
  cooperator/views/subscription_request_view.xml
  cooperator/wizard/create_subscription_from_partner.xml
Labels: bot is merging ⏳

#56 12.0 add l10n be cooperator national number
  l10n_be_cooperator_national_number/README.rst
  l10n_be_cooperator_national_number/__init__.py
  l10n_be_cooperator_national_number/__manifest__.py
  l10n_be_cooperator_national_number/i18n/l10n_be_cooperator_national_number.pot
  l10n_be_cooperator_national_number/models/__init__.py
  l10n_be_cooperator_national_number/models/company.py
  l10n_be_cooperator_national_number/models/subscription_request.py
  l10n_be_cooperator_national_number/readme/CONTRIBUTORS.rst
  l10n_be_cooperator_national_number/readme/DESCRIPTION.rst
  l10n_be_cooperator_national_number/static/description/index.html
  l10n_be_cooperator_national_number/tests/__init__.py
  l10n_be_cooperator_national_number/tests/test_cooperator_national_number.py
  l10n_be_cooperator_national_number/views/res_company_view.xml
  l10n_be_cooperator_national_number/views/subscription_request_view.xml
  l10n_be_cooperator_website_national_number/README.rst
  l10n_be_cooperator_website_national_number/__init__.py
  l10n_be_cooperator_website_national_number/__manifest__.py
  l10n_be_cooperator_website_national_number/controllers/__init__.py
  l10n_be_cooperator_website_national_number/controllers/main.py
  l10n_be_cooperator_website_national_number/i18n/l10n_be_cooperator_national_number.pot
  l10n_be_cooperator_website_national_number/readme/CONTRIBUTORS.rst
  l10n_be_cooperator_website_national_number/readme/DESCRIPTION.rst
  l10n_be_cooperator_website_national_number/static/description/index.html
  l10n_be_cooperator_website_national_number/views/subscription_template.xml
  setup/l10n_be_cooperator_national_number/odoo/addons/l10n_be_cooperator_national_number
  setup/l10n_be_cooperator_national_number/setup.py
  setup/l10n_be_cooperator_website_national_number/odoo/addons/l10n_be_cooperator_website_national_number
  setup/l10n_be_cooperator_website_national_number/setup.py
Labels: bot is merging ⏳

#52 [12.0][FIX] fix random required fields on website form
  cooperator/models/subscription_request.py
Labels: approved, bot is merging ⏳

#48 [ADD] update_partner_info to be modified by IWP
  cooperator/models/subscription_request.py
Labels: ready to merge, approved, bot is merging ⏳
