Repository OCA/cooperative, pull requests merged in 2024-05, with the labels that each got.

#126 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .oca_hooks.cfg
  .pre-commit-config.yaml
  cooperator/README.rst
  cooperator/readme/HISTORY.rst
  cooperator/static/description/index.html
Labels: help wanted, needs review, bot is merging ⏳

#119 [16.0][MIG] l10n_be_cooperator_national_number
  cooperator/models/subscription_request.py
  l10n_be_cooperator_national_number/README.rst
  l10n_be_cooperator_national_number/__init__.py
  l10n_be_cooperator_national_number/__manifest__.py
  l10n_be_cooperator_national_number/i18n/l10n_be_cooperator_national_number.pot
  l10n_be_cooperator_national_number/models/__init__.py
  l10n_be_cooperator_national_number/models/company.py
  l10n_be_cooperator_national_number/models/res_partner.py
  l10n_be_cooperator_national_number/models/subscription_request.py
  l10n_be_cooperator_national_number/readme/CONTRIBUTORS.rst
  l10n_be_cooperator_national_number/readme/DESCRIPTION.rst
  l10n_be_cooperator_national_number/readme/USAGE.rst
  l10n_be_cooperator_national_number/static/description/icon.png
  l10n_be_cooperator_national_number/static/description/index.html
  l10n_be_cooperator_national_number/tests/__init__.py
  l10n_be_cooperator_national_number/tests/test_cooperator_national_number.py
  l10n_be_cooperator_national_number/views/res_company_view.xml
  l10n_be_cooperator_national_number/views/subscription_request_view.xml
  setup/l10n_be_cooperator_national_number/odoo/addons/l10n_be_cooperator_national_number
  setup/l10n_be_cooperator_national_number/setup.py
Labels: approved, bot is merging ⏳

#69 [14.0][MIG] l10n_be_cooperator_national_number
  l10n_be_cooperator_national_number/README.rst
  l10n_be_cooperator_national_number/__init__.py
  l10n_be_cooperator_national_number/__manifest__.py
  l10n_be_cooperator_national_number/i18n/l10n_be_cooperator_national_number.pot
  l10n_be_cooperator_national_number/migrations/14.0.1.1.0/post-migration.py
  l10n_be_cooperator_national_number/models/__init__.py
  l10n_be_cooperator_national_number/models/company.py
  l10n_be_cooperator_national_number/models/res_partner.py
  l10n_be_cooperator_national_number/models/subscription_request.py
  l10n_be_cooperator_national_number/readme/CONTRIBUTORS.rst
  l10n_be_cooperator_national_number/readme/DESCRIPTION.rst
  l10n_be_cooperator_national_number/readme/USAGE.rst
  l10n_be_cooperator_national_number/static/description/icon.png
  l10n_be_cooperator_national_number/static/description/index.html
  l10n_be_cooperator_national_number/tests/__init__.py
  l10n_be_cooperator_national_number/tests/test_cooperator_national_number.py
  l10n_be_cooperator_national_number/views/res_company_view.xml
  l10n_be_cooperator_national_number/views/subscription_request_view.xml
  setup/l10n_be_cooperator_national_number/odoo/addons/l10n_be_cooperator_national_number
  setup/l10n_be_cooperator_national_number/setup.py
Labels: ready to merge, approved, no stale, bot is merging ⏳

#129 [16.0][FIX] re-add renamed get_person_info() method
  cooperator/models/subscription_request.py
Labels: bot is merging ⏳

#130 [14.0][ADD] add missing cooperator 14.0.1.0.0 migration script
  cooperator/migrations/14.0.1.0.0/post-migration.py
Labels: bot is merging ⏳
